apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgresql-ha.fullname" $ }}-primary-hl
  labels:
    {{- include "postgresql-ha.primary.labels" $ | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: tcp-postgres
      port: 5432
      targetPort: tcp-postgres
      protocol: TCP
  selector:
      {{- include "postgresql-ha.primary.selectorLabels" $ | nindent 6 }}