apiVersion: v1
entries:
  common:
    - apiVersion: v2
      name: common
      version: 1.0.0
      appVersion: "null"
      description: A Helm chart for Kubernetes
      digest: 410daa910609886ed8c84fcb87cd491f232b47c5b75b6a849174e999f48f1438
      urls:
        - oci://registry-1.docker.io/kluvtad/common:1.0.0
      sources:
        - https://github.com/kluvtad/packages/tree/4727088de1ec8923904a444b6066da26fef93e5f/helm/common
    - apiVersion: v2
      name: common
      version: 1.0.1
      appVersion: "null"
      description: A Helm chart for Kubernetes
      digest: 72bdb0968c5b6afa62ae27b3ef5812d61daf763fdac529912178a7c901a35cb6
      urls:
        - oci://registry-1.docker.io/kluvtad/common:1.0.1
      sources:
        - https://github.com/kluvtad/packages/tree/0703a55a7324eda5fa7c58bf34b5530e16b08f71/helm/common
    - apiVersion: v2
      name: common
      version: 1.1.0
      appVersion: "null"
      description: A Helm chart for Kubernetes
      digest: bb0b4793b6017f37694d3fef05144f3da947fce8886d898e09fe307e74a8c42a
      urls:
        - oci://registry-1.docker.io/kluvtad/common:1.1.0
      sources:
        - https://github.com/kluvtad/packages/tree/37f5ac15d00659940c15376052d1d8bd7d0c0d7e/helm/common
    - apiVersion: v2
      name: common
      version: 1.2.0
      appVersion: "null"
      description: A Helm chart for Kubernetes
      digest: 8fa820c76ec924a740237ca6eb87f649fec5a01dcd8109297259cc9d043c4f59
      urls:
        - oci://registry-1.docker.io/kluvtad/common:1.2.0
      sources:
        - https://github.com/kluvtad/packages/tree/23e461397cc7539da2f97910f25a26ee954c6ec6/helm/common
    - apiVersion: v2
      name: common
      version: 1.3.0-helm
      appVersion: "null"
      description: A Helm chart for Kubernetes
      digest: 4da2797d9ac2626bbc9d96ac7f3dcaba53fe0c791cd82040ef3232849ec09312
      urls:
        - oci://registry-1.docker.io/kluvtad/common:1.3.0-helm
      sources:
        - https://github.com/kluvtad/packages/tree/626e82a6ff30e9d964a7f441f4b5bf79ea1b87d7/helm/common
    - apiVersion: v2
      name: common
      version: 1.3.0-helm
      appVersion: "null"
      description: A Helm chart for Kubernetes
      digest: 4978830f02cef65e7bd81bc0fc1a1fbf9353f18be3bc14cddbcbbfa27dc6a815
      urls:
        - oci://registry-1.docker.io/kluvtad/common:1.3.0-helm
      sources:
        - https://github.com/kluvtad/packages/tree/2e9d72e4a0917d78bb2f4ca29963cfc02cd42bb9/helm/common
    - apiVersion: v2
      name: common
      version: 2.0.0-helm
      appVersion: "null"
      description: A Helm chart for Kubernetes
      digest: 78f59d1fbe3b4dcd4a9f12bbcf55253b1a6caa92d33ab16164db89349105f7d1
      urls:
        - oci://registry-1.docker.io/kluvtad/common:2.0.0-helm
      sources:
        - https://github.com/kluvtad/packages/tree/c968ed251042f4deb49204af63e1eb53513a4e66/helm/common
    - apiVersion: v2
      name: common
      version: 2.0.1-helm
      appVersion: "null"
      description: A Helm chart for Kubernetes
      digest: 56a19a8bb1dd3f4663948fae323e0a8e7f2166c8b2f1674fd9e62d77b79edfaf
      urls:
        - oci://registry-1.docker.io/kluvtad/common:2.0.1-helm
      sources:
        - https://github.com/kluvtad/packages/tree/cbb13972ae3f3c02ff70f8e0a89e86b88dad3e7d/helm/common
    - apiVersion: v2
      name: common
      version: 3.0.0-helm
      appVersion: "null"
      description: A Helm chart for Kubernetes
      digest: 56b98c371da5a712f18e71663af67a4081122542bfd3d1d5558d7d8a16f685c2
      urls:
        - oci://registry-1.docker.io/kluvtad/common:3.0.0-helm
      sources:
        - https://github.com/kluvtad/packages/tree/b748520089fd8c4292f0b6c52f2ea0376bc6196f/helm/common
  busybox:
    - apiVersion: v2
      name: busybox
      version: 0.1.0
      appVersion: 0.1.0
      description: A Helm chart for Kubernetes
      digest: 52d3a8b0fea4add2556f3b94c1b5d90f610ecc3c651cfa4a8605a0ff4eb32007
      urls:
        - oci://registry-1.docker.io/kluvtad/busybox:0.1.0
      sources:
        - https://github.com/kluvtad/packages/tree/aca99201aa7b7251c9f0f03c46364f00d4b326ff/helm/busybox
    - apiVersion: v2
      name: busybox
      version: 1.0.0-stable
      appVersion: 1.0.0
      description: A Helm chart for Kubernetes
      digest: 4b316b5f74655120f28fd68b05c67b09d7605d774627f10d4ab4bc04e8ba7c95
      urls:
        - oci://registry-1.docker.io/kluvtad/busybox:1.0.0-stable
      sources:
        - https://github.com/kluvtad/packages/tree/522416cc1fb9e574717055efcd202c6b698b4b2b/helm/busybox
    - apiVersion: v2
      name: busybox
      version: 1.1.0-helm
      appVersion: 1.1.0
      description: A Helm chart for Kubernetes
      digest: e87b51e9174bf233b9153b64ef42589a5f2dca4c357e0c1ec91e24bed96838a6
      urls:
        - oci://registry-1.docker.io/kluvtad/busybox:1.1.0-helm
      sources:
        - https://github.com/kluvtad/packages/tree/626e82a6ff30e9d964a7f441f4b5bf79ea1b87d7/helm/busybox
    - apiVersion: v2
      name: busybox
      version: 1.1.0-helm
      appVersion: 1.1.0
      description: A Helm chart for Kubernetes
      digest: bb2d07d67ecd5822dabe806b64db2038f605a5dc7d116ee22f59ba3ab830a03a
      urls:
        - oci://registry-1.docker.io/kluvtad/busybox:1.1.0-helm
      sources:
        - https://github.com/kluvtad/packages/tree/2e9d72e4a0917d78bb2f4ca29963cfc02cd42bb9/helm/busybox
generated: 2025-06-24T01:34:48Z
