apiVersion: v1
entries:
  common:
    - apiVersion: v2
      name: common
      version: 1.0.0
      appVersion: "null"
      description: A Helm chart for Kubernetes
      digest: 410daa910609886ed8c84fcb87cd491f232b47c5b75b6a849174e999f48f1438
      urls:
        - oci://registry-1.docker.io/kluvtad/common:1.0.0
      sources:
        - https://github.com/kluvtad/packages/tree/4727088de1ec8923904a444b6066da26fef93e5f/helm/common
    - apiVersion: v2
      name: common
      version: 1.0.1
      appVersion: "null"
      description: A Helm chart for Kubernetes
      digest: 72bdb0968c5b6afa62ae27b3ef5812d61daf763fdac529912178a7c901a35cb6
      urls:
        - oci://registry-1.docker.io/kluvtad/common:1.0.1
      sources:
        - https://github.com/kluvtad/packages/tree/0703a55a7324eda5fa7c58bf34b5530e16b08f71/helm/common
    - apiVersion: v2
      name: common
      version: 1.1.0
      appVersion: "null"
      description: A Helm chart for Kubernetes
      digest: bb0b4793b6017f37694d3fef05144f3da947fce8886d898e09fe307e74a8c42a
      urls:
        - oci://registry-1.docker.io/kluvtad/common:1.1.0
      sources:
        - https://github.com/kluvtad/packages/tree/37f5ac15d00659940c15376052d1d8bd7d0c0d7e/helm/common
    - apiVersion: v2
      name: common
      version: 1.2.0
      appVersion: "null"
      description: A Helm chart for Kubernetes
      digest: 8fa820c76ec924a740237ca6eb87f649fec5a01dcd8109297259cc9d043c4f59
      urls:
        - oci://registry-1.docker.io/kluvtad/common:1.2.0
      sources:
        - https://github.com/kluvtad/packages/tree/23e461397cc7539da2f97910f25a26ee954c6ec6/helm/common
    - apiVersion: v2
      name: common
      version: 1.3.0-helm
      appVersion: "null"
      description: A Helm chart for Kubernetes
      digest: 4da2797d9ac2626bbc9d96ac7f3dcaba53fe0c791cd82040ef3232849ec09312
      urls:
        - oci://registry-1.docker.io/kluvtad/common:1.3.0-helm
      sources:
        - https://github.com/kluvtad/packages/tree/626e82a6ff30e9d964a7f441f4b5bf79ea1b87d7/helm/common
    - apiVersion: v2
      name: common
      version: 1.3.0-helm
      appVersion: "null"
      description: A Helm chart for Kubernetes
      digest: 4978830f02cef65e7bd81bc0fc1a1fbf9353f18be3bc14cddbcbbfa27dc6a815
      urls:
        - oci://registry-1.docker.io/kluvtad/common:1.3.0-helm
      sources:
        - https://github.com/kluvtad/packages/tree/2e9d72e4a0917d78bb2f4ca29963cfc02cd42bb9/helm/common
    - apiVersion: v2
      name: common
      version: 2.0.0-helm
      appVersion: "null"
      description: A Helm chart for Kubernetes
      digest: 78f59d1fbe3b4dcd4a9f12bbcf55253b1a6caa92d33ab16164db89349105f7d1
      urls:
        - oci://registry-1.docker.io/kluvtad/common:2.0.0-helm
      sources:
        - https://github.com/kluvtad/packages/tree/c968ed251042f4deb49204af63e1eb53513a4e66/helm/common
    - apiVersion: v2
      name: common
      version: 2.0.1-helm
      appVersion: "null"
      description: A Helm chart for Kubernetes
      digest: 56a19a8bb1dd3f4663948fae323e0a8e7f2166c8b2f1674fd9e62d77b79edfaf
      urls:
        - oci://registry-1.docker.io/kluvtad/common:2.0.1-helm
      sources:
        - https://github.com/kluvtad/packages/tree/cbb13972ae3f3c02ff70f8e0a89e86b88dad3e7d/helm/common
    - apiVersion: v2
      name: common
      version: 3.0.0-helm
      appVersion: "null"
      description: A Helm chart for Kubernetes
      digest: 56b98c371da5a712f18e71663af67a4081122542bfd3d1d5558d7d8a16f685c2
      urls:
        - oci://registry-1.docker.io/kluvtad/common:3.0.0-helm
      sources:
        - https://github.com/kluvtad/packages/tree/b748520089fd8c4292f0b6c52f2ea0376bc6196f/helm/common
    - apiVersion: v2
      name: common
      version: 3.1.0-helm
      appVersion: "null"
      description: A Helm chart for Kubernetes
      digest: f373cadc0bd5968eaf1db958c2776f96cd6d8ab474f88398eb00189d8237001c
      urls:
        - oci://registry-1.docker.io/kluvtad/common:3.1.0-helm
      sources:
        - https://github.com/kluvtad/packages/tree/cf6f6c1419f8be84a8a92d2161515f6a6b7e3d77/helm/common
  busybox:
    - apiVersion: v2
      name: busybox
      version: 0.1.0
      appVersion: 0.1.0
      description: A Helm chart for Kubernetes
      digest: 52d3a8b0fea4add2556f3b94c1b5d90f610ecc3c651cfa4a8605a0ff4eb32007
      urls:
        - oci://registry-1.docker.io/kluvtad/busybox:0.1.0
      sources:
        - https://github.com/kluvtad/packages/tree/aca99201aa7b7251c9f0f03c46364f00d4b326ff/helm/busybox
    - apiVersion: v2
      name: busybox
      version: 1.0.0-stable
      appVersion: 1.0.0
      description: A Helm chart for Kubernetes
      digest: 4b316b5f74655120f28fd68b05c67b09d7605d774627f10d4ab4bc04e8ba7c95
      urls:
        - oci://registry-1.docker.io/kluvtad/busybox:1.0.0-stable
      sources:
        - https://github.com/kluvtad/packages/tree/522416cc1fb9e574717055efcd202c6b698b4b2b/helm/busybox
    - apiVersion: v2
      name: busybox
      version: 1.1.0-helm
      appVersion: 1.1.0
      description: A Helm chart for Kubernetes
      digest: e87b51e9174bf233b9153b64ef42589a5f2dca4c357e0c1ec91e24bed96838a6
      urls:
        - oci://registry-1.docker.io/kluvtad/busybox:1.1.0-helm
      sources:
        - https://github.com/kluvtad/packages/tree/626e82a6ff30e9d964a7f441f4b5bf79ea1b87d7/helm/busybox
    - apiVersion: v2
      name: busybox
      version: 1.1.0-helm
      appVersion: 1.1.0
      description: A Helm chart for Kubernetes
      digest: bb2d07d67ecd5822dabe806b64db2038f605a5dc7d116ee22f59ba3ab830a03a
      urls:
        - oci://registry-1.docker.io/kluvtad/busybox:1.1.0-helm
      sources:
        - https://github.com/kluvtad/packages/tree/2e9d72e4a0917d78bb2f4ca29963cfc02cd42bb9/helm/busybox
    - apiVersion: v2
      name: busybox
      version: 1.2.0-helm
      appVersion: 1.1.0
      description: A Helm chart for Kubernetes
      digest: e7217f2bbdf7fcc8cfb30286e9b6cca43ae208b1eda139e205a71e9097665329
      urls:
        - oci://registry-1.docker.io/kluvtad/busybox:1.2.0-helm
      sources:
        - https://github.com/kluvtad/packages/tree/a35ace031e12139ce8d7ccf7493a1433f8e99e92/helm/busybox
    - apiVersion: v2
      name: busybox
      version: 1.3.0-helm
      appVersion: 1.1.0
      description: A Helm chart for Kubernetes
      digest: 01b9b9839316e8f047376033a00787f7c168e9b8bbc614ffd7b25062841b1ab0
      urls:
        - oci://ghcr.io/kluvtad/packages/helm/busybox:1.3.0-helm
      sources:
        - https://github.com/kluvtad/packages/tree/a212053c8589d866fff25f18048c0d54019929ce/helm/busybox
  postgresql-ha:
    - apiVersion: v2
      name: postgresql-ha
      version: 0.1.0-helm
      appVersion: 17.4-bookworm
      description: A Helm chart for Kubernetes
      digest: cae3ec53e837631ebd0e81be870476cfef90d6c8352ceb33e40004c087bce024
      urls:
        - oci://registry-1.docker.io/kluvtad/postgresql-ha:0.1.0-helm
      sources:
        - https://github.com/kluvtad/packages/tree/3c4cd99a391321f1a2e4ac3fada6cc5635b0c416/helm/postgresql-ha
    - apiVersion: v2
      name: postgresql-ha
      version: 0.3.0-helm
      appVersion: 17.4-bookworm
      description: A Helm chart for Kubernetes
      digest: 0ec0573640d3b0b9838b6f722316df28f2c3338d600112ea2428e7d6280edb3e
      urls:
        - oci://registry-1.docker.io/kluvtad/postgresql-ha:0.3.0-helm
      sources:
        - https://github.com/kluvtad/packages/tree/244c9d1f8b0b31339730291793c846369171697f/helm/postgresql-ha
    - apiVersion: v2
      name: postgresql-ha
      version: 0.3.1-helm
      appVersion: 17.4-bookworm
      description: A Helm chart for Kubernetes
      digest: 6660e235dc8a073fa087d7c1de1c72bacbb1f96c055cd4113491684d76c023ca
      urls:
        - oci://registry-1.docker.io/kluvtad/postgresql-ha:0.3.1-helm
      sources:
        - https://github.com/kluvtad/packages/tree/76253ce1c331093564671d7c5f3794eadf9ec463/helm/postgresql-ha
    - apiVersion: v2
      name: postgresql-ha
      version: 0.3.2-helm
      appVersion: 17.4-bookworm
      description: A Helm chart for Kubernetes
      digest: 1bf5e465f5727e4a347a2e315f50cdc62cd44cefe60dab890b339aa4828167f3
      urls:
        - oci://registry-1.docker.io/kluvtad/postgresql-ha:0.3.2-helm
      sources:
        - https://github.com/kluvtad/packages/tree/eda4f9eadf9ba0fb1446d1df60ef967c9b66678c/helm/postgresql-ha
    - apiVersion: v2
      name: postgresql-ha
      version: 0.3.3-helm
      appVersion: 17.4-bookworm
      description: A Helm chart for Kubernetes
      digest: 0b1ee427a6240b499fea5bfe66c4df0b07308e66573627d0c4029e5899e49b5b
      urls:
        - oci://registry-1.docker.io/kluvtad/postgresql-ha:0.3.3-helm
      sources:
        - https://github.com/kluvtad/packages/tree/61fdd6dbbcda891943bed09a2966132db341c197/helm/postgresql-ha
    - apiVersion: v2
      name: postgresql-ha
      version: 0.4.0-helm
      appVersion: 17.4-bookworm
      description: A Helm chart for Kubernetes
      digest: ac86b17b207ccb19e922d852f1518eadb62c3f9e7eeda81487723be418aeba4e
      urls:
        - oci://registry-1.docker.io/kluvtad/postgresql-ha:0.4.0-helm
      sources:
        - https://github.com/kluvtad/packages/tree/bd895545541e713063c87fc88c97d0cd645368a9/helm/postgresql-ha
    - apiVersion: v2
      name: postgresql-ha
      version: 0.4.2-helm
      appVersion: 17.4-bookworm
      description: A Helm chart for Kubernetes
      digest: 38d3f7b9be1881bef49b4575951f7883fe064ce9910cee966265dd2cc92c3dea
      urls:
        - oci://registry-1.docker.io/kluvtad/postgresql-ha:0.4.2-helm
      sources:
        - https://github.com/kluvtad/packages/tree/5a964744160b9ea3ca96b9bd334faea0b7970c9b/helm/postgresql-ha
    - apiVersion: v2
      name: postgresql-ha
      version: 0.5.0-helm
      appVersion: 17.4-bookworm
      description: A Helm chart for Kubernetes
      digest: 0f315b93f52ddfaf75764c97237f954360027d7bd4b154ddcceb7f019088604a
      urls:
        - oci://registry-1.docker.io/kluvtad/postgresql-ha:0.5.0-helm
      sources:
        - https://github.com/kluvtad/packages/tree/391043686581a242c2413283347fafad24240d6d/helm/postgresql-ha
    - apiVersion: v2
      name: postgresql-ha
      version: 0.5.1-helm
      appVersion: 17.4-bookworm
      description: A Helm chart for Kubernetes
      digest: 7712ed0c1f1b7bb2f980dbd4e3e70effb34a9fe166bf5a54e2035f90264eec64
      urls:
        - oci://registry-1.docker.io/kluvtad/postgresql-ha:0.5.1-helm
      sources:
        - https://github.com/kluvtad/packages/tree/fccc564f1f4a547ea929c406b64cc3982e6f14ca/helm/postgresql-ha
    - apiVersion: v2
      name: postgresql-ha
      version: 0.6.0-helm
      appVersion: "null"
      description: A Helm chart for Kubernetes
      digest: d7fad8efdf6d8088d9f8ae66f476fd5d1a6527db8295d44f15d7e0be3511d8ac
      urls:
        - oci://ghcr.io/kluvtad/packages/helm/postgresql-ha:0.6.0-helm
      sources:
        - https://github.com/kluvtad/packages/tree/29e72583a5bf90b728c014f4046cd4edb5f419e8/helm/postgresql-ha
    - apiVersion: v2
      name: postgresql-ha
      version: 0.6.0-helm
      appVersion: "null"
      description: A Helm chart for Kubernetes
      digest: 1b04507e2921a7b94ff4b6d62eeabaaf75981e61a8e33b512423b7bcb05eecd9
      urls:
        - oci://registry-1.docker.io/kluvtad/postgresql-ha:0.6.0-helm
      sources:
        - https://github.com/kluvtad/packages/tree/5b165baf4b87a99bd3963aa75224c4db42565957/helm/postgresql-ha
    - apiVersion: v2
      name: postgresql-ha
      version: 1.0.0-helm
      appVersion: "null"
      description: A Helm chart for Kubernetes
      digest: 8c1459fe99258f6859bf89a20ca43de2f274ca83e2f1fd2a173cc7dd8e24bfff
      urls:
        - oci://registry-1.docker.io/kluvtad/postgresql-ha:1.0.0-helm
      sources:
        - https://github.com/kluvtad/packages/tree/0ac6ba45b81a20bd8d8ff9e81806597f1f549de9/helm/postgresql-ha
generated: 2025-11-08T08:10:18Z
