apiVersion: v1
entries:
  postgresql-ha:
    - apiVersion: v2
      name: postgresql-ha
      version: 0.5.1-helm-dev-18848677878
      appVersion: 17.4-bookworm
      description: A Helm chart for Kubernetes
      digest: d783f9d61157b95e8a0f472339cd51bed0fef4e6973e5e677123e9edc259112f
      urls:
        - oci://ghcr.io/kluvtad/packages/helm/postgresql-ha:0.5.1-helm-dev-18848677878
      sources:
        - https://github.com/kluvtad/packages/tree/fccc564f1f4a547ea929c406b64cc3982e6f14ca/helm/postgresql-ha
    - apiVersion: v2
      name: postgresql-ha
      version: 0.5.1-helm-dev-18848677878
      appVersion: 17.4-bookworm
      description: A Helm chart for Kubernetes
      digest: 988533934837a565bb220aed3f1703af3347d6a757c4bb30d107507031387ff6
      urls:
        - oci://ghcr.io/kluvtad/packages/helm/postgresql-ha:0.5.1-helm-dev-18848677878
      sources:
        - https://github.com/kluvtad/packages/tree/fccc564f1f4a547ea929c406b64cc3982e6f14ca/helm/postgresql-ha
    - apiVersion: v2
      name: postgresql-ha
      version: 0.5.1-helm-dev-18895923426
      appVersion: "null"
      description: A Helm chart for Kubernetes
      digest: e94fc5f060af418e29422cf07081aacac35a29c9362e573bdf83d12ce73c07f0
      urls:
        - oci://ghcr.io/kluvtad/packages/helm/postgresql-ha:0.5.1-helm-dev-18895923426
      sources:
        - https://github.com/kluvtad/packages/tree/4176829aecfcadaeda7cedc987a31277372adc58/helm/postgresql-ha
    - apiVersion: v2
      name: postgresql-ha
      version: 0.6.0-helm-dev-19056496039
      appVersion: "null"
      description: A Helm chart for Kubernetes
      digest: ef34459e6690996b36d49ea3b3c24199717e40923bb999f100bdcb191855f86a
      urls:
        - oci://ghcr.io/kluvtad/packages/helm/postgresql-ha:0.6.0-helm-dev-19056496039
      sources:
        - https://github.com/kluvtad/packages/tree/11e15417132aa93796affd2fa7866b403da96d10/helm/postgresql-ha
    - apiVersion: v2
      name: postgresql-ha
      version: 0.6.0-helm-dev-19056765496
      appVersion: "null"
      description: A Helm chart for Kubernetes
      digest: 63092be2112db7273828c37d62243504e0ccee71bf69c5c66e1eab13b12e2cfd
      urls:
        - oci://ghcr.io/kluvtad/packages/helm/postgresql-ha:0.6.0-helm-dev-19056765496
      sources:
        - https://github.com/kluvtad/packages/tree/398d8fd3dbcbc1b7be12009ff752de257454b412/helm/postgresql-ha
    - apiVersion: v2
      name: postgresql-ha
      version: 0.6.0-helm-dev-19057475663
      appVersion: "null"
      description: A Helm chart for Kubernetes
      digest: cf816ea3c943dabe05aaba25ce07241810edc2bfb0d9216299c0615825ca6046
      urls:
        - oci://ghcr.io/kluvtad/packages/helm/postgresql-ha:0.6.0-helm-dev-19057475663
      sources:
        - https://github.com/kluvtad/packages/tree/789fcbdfa7bc227792c28e5fab041a225b05821c/helm/postgresql-ha
generated: 2025-11-04T04:08:12Z
