apiVersion: v1
entries:
  postgresql-ha:
    - apiVersion: v2
      name: postgresql-ha
      version: 0.5.1-helm-dev-18848677878
      appVersion: 17.4-bookworm
      description: A Helm chart for Kubernetes
      digest: d783f9d61157b95e8a0f472339cd51bed0fef4e6973e5e677123e9edc259112f
      urls:
        - oci://ghcr.io/kluvtad/packages/helm/postgresql-ha:0.5.1-helm-dev-18848677878
      sources:
        - https://github.com/kluvtad/packages/tree/fccc564f1f4a547ea929c406b64cc3982e6f14ca/helm/postgresql-ha
    - apiVersion: v2
      name: postgresql-ha
      version: 0.5.1-helm-dev-18848677878
      appVersion: 17.4-bookworm
      description: A Helm chart for Kubernetes
      digest: 988533934837a565bb220aed3f1703af3347d6a757c4bb30d107507031387ff6
      urls:
        - oci://ghcr.io/kluvtad/packages/helm/postgresql-ha:0.5.1-helm-dev-18848677878
      sources:
        - https://github.com/kluvtad/packages/tree/fccc564f1f4a547ea929c406b64cc3982e6f14ca/helm/postgresql-ha
    - apiVersion: v2
      name: postgresql-ha
      version: 0.5.1-helm-dev-18895923426
      appVersion: "null"
      description: A Helm chart for Kubernetes
      digest: e94fc5f060af418e29422cf07081aacac35a29c9362e573bdf83d12ce73c07f0
      urls:
        - oci://ghcr.io/kluvtad/packages/helm/postgresql-ha:0.5.1-helm-dev-18895923426
      sources:
        - https://github.com/kluvtad/packages/tree/4176829aecfcadaeda7cedc987a31277372adc58/helm/postgresql-ha
    - apiVersion: v2
      name: postgresql-ha
      version: 0.6.0-helm-dev-19056496039
      appVersion: "null"
      description: A Helm chart for Kubernetes
      digest: ef34459e6690996b36d49ea3b3c24199717e40923bb999f100bdcb191855f86a
      urls:
        - oci://ghcr.io/kluvtad/packages/helm/postgresql-ha:0.6.0-helm-dev-19056496039
      sources:
        - https://github.com/kluvtad/packages/tree/11e15417132aa93796affd2fa7866b403da96d10/helm/postgresql-ha
    - apiVersion: v2
      name: postgresql-ha
      version: 0.6.0-helm-dev-19056765496
      appVersion: "null"
      description: A Helm chart for Kubernetes
      digest: 63092be2112db7273828c37d62243504e0ccee71bf69c5c66e1eab13b12e2cfd
      urls:
        - oci://ghcr.io/kluvtad/packages/helm/postgresql-ha:0.6.0-helm-dev-19056765496
      sources:
        - https://github.com/kluvtad/packages/tree/398d8fd3dbcbc1b7be12009ff752de257454b412/helm/postgresql-ha
    - apiVersion: v2
      name: postgresql-ha
      version: 0.6.0-helm-dev-19057475663
      appVersion: "null"
      description: A Helm chart for Kubernetes
      digest: cf816ea3c943dabe05aaba25ce07241810edc2bfb0d9216299c0615825ca6046
      urls:
        - oci://ghcr.io/kluvtad/packages/helm/postgresql-ha:0.6.0-helm-dev-19057475663
      sources:
        - https://github.com/kluvtad/packages/tree/789fcbdfa7bc227792c28e5fab041a225b05821c/helm/postgresql-ha
    - apiVersion: v2
      name: postgresql-ha
      version: 0.6.0-helm-dev-19057796613
      appVersion: "null"
      description: A Helm chart for Kubernetes
      digest: 74616671fae9dce020cb76de39055876ddc2563f28e03fdeccdfbbcef208e659
      urls:
        - oci://ghcr.io/kluvtad/packages/helm/postgresql-ha:0.6.0-helm-dev-19057796613
      sources:
        - https://github.com/kluvtad/packages/tree/6af9d40174a53d3900753e67fd03ebed2a8ba6dc/helm/postgresql-ha
    - apiVersion: v2
      name: postgresql-ha
      version: 0.6.0-helm-dev-19057853001
      appVersion: "null"
      description: A Helm chart for Kubernetes
      digest: 0792123b23ee192ea088ca3910d8ae57851e89fc004e22c0ae020b11983b48da
      urls:
        - oci://ghcr.io/kluvtad/packages/helm/postgresql-ha:0.6.0-helm-dev-19057853001
      sources:
        - https://github.com/kluvtad/packages/tree/405a78e6c4a5830e4078ae1d72cf250a5084cd98/helm/postgresql-ha
    - apiVersion: v2
      name: postgresql-ha
      version: 0.6.0-helm-dev-19061022217
      appVersion: "null"
      description: A Helm chart for Kubernetes
      digest: 57af2146758235ce1f9c190f062e7ac2fbe4ea72739fbe31c76e0223ad2b6abf
      urls:
        - oci://ghcr.io/kluvtad/packages/helm/postgresql-ha:0.6.0-helm-dev-19061022217
      sources:
        - https://github.com/kluvtad/packages/tree/435e16c11c7e717ae5fabfdbcaa0f30ac4ceddda/helm/postgresql-ha
    - apiVersion: v2
      name: postgresql-ha
      version: 0.6.0-helm-dev-19061566499
      appVersion: "null"
      description: A Helm chart for Kubernetes
      digest: 80e00d5d0ac4b2a86aa3ba7a4014fa800a1f2562650549ea1cdfa12d0f64ff88
      urls:
        - oci://ghcr.io/kluvtad/packages/helm/postgresql-ha:0.6.0-helm-dev-19061566499
      sources:
        - https://github.com/kluvtad/packages/tree/56c3e94c5639286ade1587fe5fcca2b77e7c8a7b/helm/postgresql-ha
  busybox:
    - apiVersion: v2
      name: busybox
      version: 1.3.0-helm-dev-19128867364
      appVersion: 1.1.0
      description: A Helm chart for Kubernetes
      digest: 855083c2b00729f21ebc79fdb34827e57b3d3ccd0bffdda75879cd418abb64af
      urls:
        - oci://ghcr.io/kluvtad/packages/helm/busybox:1.3.0-helm-dev-19128867364
      sources:
        - https://github.com/kluvtad/packages/tree/6f4733af1b9290e246c3919c972b261b4afe08ee/helm/busybox
generated: 2025-11-06T08:04:19Z
